# Generated by Django 2.0.2 on 2018-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, max_length=5000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'db_table': 'studios',
            },
        ),
    ]
