# Generated by Django 2.0.2 on 2018-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', max_length=5000, verbose_name='описание')),
                ('alias', models.TextField(max_length=30, verbose_name='алиас (до 30 символов)')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Longevity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('min_length', models.IntegerField(blank=True, null=True, verbose_name='минимальная продолжительность')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='максимальная продолжительность')),
                ('alias', models.TextField(max_length=30, verbose_name='алиас (до 30 символов)')),
            ],
            options={
                'verbose_name': 'Продолжительность',
                'verbose_name_plural': 'Продолжительности',
                'db_table': 'longevity',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', max_length=5000, verbose_name='описание')),
                ('alias', models.TextField(max_length=30, verbose_name='алиас (до 30 символов)')),
            ],
            options={
                'verbose_name': 'Персоналия',
                'verbose_name_plural': 'Персоналии',
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'staff_roles',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', max_length=5000, verbose_name='описание')),
                ('alias', models.TextField(max_length=30, verbose_name='алиас (до 30 символов)')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'db_table': 'studios',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', max_length=5000, verbose_name='описание')),
                ('alias', models.TextField(max_length=30, verbose_name='алиас (до 30 символов)')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TranslationLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='Направление перевода (в свободной форме)')),
            ],
            options={
                'verbose_name': 'Направление перевода',
                'verbose_name_plural': 'Направления перевода',
                'db_table': 'translation_languages',
            },
        ),
    ]
