# Generated by Django 2.0.2 on 2018-06-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0002_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='Переводчик')),
                ('description', models.TextField(max_length=5000, verbose_name='описание', blank=True, default='')),
                ('alias', models.TextField(max_length=30, verbose_name='алиас (до 30 символов)')),
            ],
            options={
                'verbose_name': 'Переводчик',
                'verbose_name_plural': 'Переводчики',
                'db_table': 'translator_teams',
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('title',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('title',), 'verbose_name': 'Персоналия', 'verbose_name_plural': 'Персоналии'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ('title',), 'verbose_name': 'Студия', 'verbose_name_plural': 'Студии'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('title',), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
