# Generated by Django 2.0.2 on 2018-03-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0004_create_staffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'staff_roles',
            },
        ),
    ]
