# Generated by Django 2.0.2 on 2018-03-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0005_create_staff_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='Направление перевода (в свободной форме)')),
            ],
            options={
                'verbose_name': 'Направление перевода',
                'verbose_name_plural': 'Направления перевода',
                'db_table': 'translation_languages',
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Персоналия', 'verbose_name_plural': 'Персоналии'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default='', max_length=5000, verbose_name='описание'),
        ),
    ]
