# Generated by Django 2.0.2 on 2018-03-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0006_add_translation_languages_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Longevity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('min_length', models.IntegerField(blank=True, null=True, verbose_name='минимальная продолжительность')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='максимальная продолжительность')),
            ],
            options={
                'verbose_name': 'Продолжительность',
                'verbose_name_plural': 'Продолжительности',
                'db_table': 'longevity',
            },
        ),
    ]
