# Generated by Django 2.0.2 on 2018-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0007_add_longevity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='alias',
            field=models.TextField(default='', max_length=30, verbose_name='алиас (до 30 символов)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='alias',
            field=models.TextField(default='', max_length=30, verbose_name='алиас (до 30 символов)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='alias',
            field=models.TextField(default='', max_length=30, verbose_name='алиас (до 30 символов)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='alias',
            field=models.TextField(default='', max_length=30, verbose_name='алиас (до 30 символов)'),
        ),
    ]
