# Generated by Django 2.0.2 on 2018-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0010_add_longevity_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='longevity',
            name='alias',
            field=models.TextField(default='', max_length=30, verbose_name='алиас (до 30 символов)'),
        ),
    ]
