# Generated by Django 2.0.2 on 2018-05-23 14:34

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sanitizer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('alias', models.CharField(blank=True, default='', max_length=30, verbose_name='Алиас (до 30 символов)')),
                ('poster', core.fields.ImageFieldWithEnhancedUploadTo(blank=True, null=True, verbose_name='Постер')),
                ('short_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Краткое описание')),
                ('description', sanitizer.models.SanitizedTextField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания новости')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
    ]
