# Generated by Django 2.0.2 on 2018-06-10 16:28

from django.db import migrations
import sanitizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_change_description_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=sanitizer.models.SanitizedTextField(blank=True, default='', max_length=512, verbose_name='Краткое описание'),
        ),
    ]
