# Generated by Django 2.0.2 on 2018-04-25 20:39

import bitfield.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('send_distributions', models.BooleanField(default=False, verbose_name='Отправлять рассылку')),
                ('send_time', models.TimeField(default=datetime.time(10, 30), verbose_name='Время рассылки')),
                ('weekdays', bitfield.models.BitField((('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')), default=127, verbose_name='Битовый код дней рассылки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'user_profile',
            },
        ),
    ]
