# Generated by Django 2.0.2 on 2018-08-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_change_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vk_link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на страницу ВК'),
        ),
    ]
