# Generated by Django 2.0.2 on 2018-08-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_vk_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='VK ID страницы'),
        ),
    ]
