# Generated by Django 2.0.2 on 2018-04-20 14:00

import bitfield.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_all_profiles_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='profile',
            name='send_distributions',
            field=models.BooleanField(default=False, verbose_name='Отправлять рассылку'),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_time',
            field=models.TimeField(default=datetime.time(10, 30), verbose_name='Время рассылки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekdays',
            field=bitfield.models.BitField((('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскреснье')), default=127, verbose_name='Битовый код дней рассылки'),
        ),
    ]
