# Generated by Django 2.0.2 on 2018-04-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0013_add_moderator_field'),
        ('core', '0004_all_profiles_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='translation.TranslationItem', verbose_name='Подписки на рассылку'),
        ),
    ]
