# Generated by Django 2.0.2 on 2018-08-23 09:34

from django.db import migrations, models


def delete_notification_settings(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.all().update(send_distributions=False, weekdays=0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_change_timefield_to_int'),
        ('notifications', '0002_delete_all_mailing_crontabs'),
    ]

    operations = [
        migrations.RunPython(delete_notification_settings, migrations.RunPython.noop),
    ]
