# Generated by Django 2.0.2 on 2018-04-23 12:23

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_distributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weekdays',
            field=bitfield.models.BitField((('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')), default=127, verbose_name='Битовый код дней рассылки'),
        ),
    ]
