# Generated by Django 2.0.4 on 2018-12-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_notification_settings_for_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vk_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vk_link',
        ),
    ]
