# Generated by Django 2.0.2 on 2018-04-28 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_new_profile_model'),
        ('vn_core', '0002_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationBetaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('comment', models.TextField(blank=True, default='', max_length=2000, verbose_name='Комментарий')),
                ('approved', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('rejected', models.BooleanField(default=False, verbose_name='Отклонена')),
                ('last_update', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Ссылка на патч',
                'verbose_name_plural': 'Ссылки на патчи',
                'db_table': 'statistics_betalink',
            },
        ),
        migrations.CreateModel(
            name='TranslationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('moderators', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Модераторы')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'db_table': 'translation_items',
            },
        ),
        migrations.CreateModel(
            name='TranslationStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.IntegerField(default=0)),
                ('pictures_statistics', models.TextField(blank=True, default='', max_length=500, verbose_name='Статистика изображений')),
                ('technical_statistics', models.TextField(blank=True, default='', max_length=500, verbose_name='Статистика тех. части')),
                ('comment', models.TextField(blank=True, default='', max_length=2000, verbose_name='Статистика изображений')),
                ('last_update', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего обновления')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Всего строк')),
                ('translated', models.IntegerField(default=0, verbose_name='Переведено')),
                ('edited_first_pass', models.IntegerField(default=0, verbose_name='Первый проход редактуры')),
                ('edited_second_pass', models.IntegerField(default=0, verbose_name='Второй проход редактуры')),
            ],
            options={
                'db_table': 'statistics_item',
            },
        ),
        migrations.CreateModel(
            name='TranslationStatisticsChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Пользовательское название')),
                ('script_title', models.CharField(max_length=50, verbose_name='Имя скрипта')),
                ('is_chapter', models.BooleanField(default=False)),
                ('total_rows', models.IntegerField(default=0)),
                ('translated', models.IntegerField(default=0)),
                ('edited_first_pass', models.IntegerField(default=0)),
                ('edited_second_pass', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего обновления')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='translation.TranslationStatisticsChapter')),
            ],
            options={
                'db_table': 'statistics_chapter',
            },
        ),
        migrations.CreateModel(
            name='TranslationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations_set', to='translation.TranslationItem')),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки',
                'db_table': 'translation_subscriptions',
            },
        ),
        migrations.AddField(
            model_name='translationitem',
            name='statistics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translation.TranslationStatistics', verbose_name='Привязанная статистика'),
        ),
        migrations.AddField(
            model_name='translationitem',
            name='subscriber',
            field=models.ManyToManyField(blank=True, through='translation.TranslationSubscription', to='core.Profile', verbose_name='Подписчики'),
        ),
        migrations.AddField(
            model_name='translationitem',
            name='visual_novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vn_core.VisualNovel', verbose_name='Визуальная новелла'),
        ),
        migrations.AddField(
            model_name='translationbetalink',
            name='translation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='translation.TranslationItem'),
        ),
    ]
