# Generated by Django 2.0.2 on 2018-03-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vn_core', '0003_add_many_to_many_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('visual_novel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vn_core.VisualNovel')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'db_table': 'translation_items',
            },
        ),
    ]
