# Generated by Django 2.0.2 on 2018-03-14 15:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_add_translation_item_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.IntegerField(default=0)),
                ('pictures_statistics', models.TextField(default='', max_length=500, verbose_name='Статистика изображений')),
                ('technical_statistics', models.TextField(default='', max_length=500, verbose_name='Статистика тех. части')),
                ('comment', models.TextField(default='', max_length=2000, verbose_name='Статистика изображений')),
            ],
            options={
                'db_table': 'statistics_item',
            },
        ),
        migrations.CreateModel(
            name='TranslationStatisticsChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('script_title', models.CharField(default='', max_length=50)),
                ('is_chapter', models.BooleanField(default=False)),
                ('total_rows', models.IntegerField(default=0)),
                ('translated', models.IntegerField(default=0)),
                ('edited_first_pass', models.IntegerField(default=0)),
                ('edited_second_pass', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='translation.TranslationStatisticsChapter')),
            ],
            options={
                'db_table': 'statistics_chapter',
            },
        ),
        migrations.AddField(
            model_name='translationitem',
            name='statistics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='translation.TranslationStatistics'),
        ),
    ]
