# Generated by Django 2.0.2 on 2018-06-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationItemSendToVK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_group_id', models.CharField(default='', max_length=255, verbose_name='ID группы ВК')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('pictures_statistics', models.TextField(blank=True, default='', max_length=500, verbose_name='Статистика изображений')),
                ('technical_statistics', models.TextField(blank=True, default='', max_length=500, verbose_name='Статистика тех. части')),
                ('comment', models.TextField(blank=True, default='', max_length=2000, verbose_name='Статистика изображений')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Всего строк')),
                ('translated', models.IntegerField(default=0, verbose_name='Переведено')),
                ('edited_first_pass', models.IntegerField(default=0, verbose_name='Первый проход редактуры')),
                ('edited_second_pass', models.IntegerField(default=0, verbose_name='Второй проход редактуры')),
                ('translation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.TranslationItem', verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Перевод отпраленный в группу ВК',
                'verbose_name_plural': 'Переводы отпраленные в группы ВК',
                'db_table': 'translation_item_send_to_vk',
            },
        ),
    ]
