# Generated by Django 2.0.2 on 2018-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_add_statistics_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationBetaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=200)),
                ('comment', models.TextField(default='', max_length=2000)),
            ],
            options={
                'db_table': 'statistics_betalink',
            },
        ),
        migrations.AddField(
            model_name='translationitem',
            name='beta_patches',
            field=models.ManyToManyField(blank=True, to='translation.TranslationBetaLink'),
        ),
    ]
