# Generated by Django 2.0.2 on 2018-03-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_add_betapatchlink_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationitem',
            name='beta_patches',
        ),
        migrations.AddField(
            model_name='translationbetalink',
            name='translation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='translation.TranslationItem'),
        ),
    ]
