# Generated by Django 2.0.2 on 2018-07-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_add_translators_to_translation_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationbetalink',
            name='translation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='translation.TranslationItem', verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='translationsubscription',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='translationsubscription',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations_set', to='translation.TranslationItem', verbose_name='Перевод'),
        ),
    ]
