# Generated by Django 2.0.2 on 2018-08-01 17:17

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_change_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationitem',
            name='status',
            field=bitfield.models.BitField((('active', 'Активный'), ('frozen', 'Замороженный'), ('onhold', 'Давно не обновлялся'), ('finished', 'Завершен'), ('readytogo', 'Готовится к выпуску'), ('intest', 'Тестирование'), ('dropped', 'Заброшен')), default=1, verbose_name='Битовый код статуса'),
        ),
        migrations.AddField(
            model_name='translationitemsendtovk',
            name='status',
            field=models.IntegerField(default=1, verbose_name='Статус перевода'),
        ),
    ]
