# Generated by Django 2.0.2 on 2018-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_add_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationstatistics',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
