# Generated by Django 2.0.2 on 2018-03-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_add_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationstatistics',
            name='edited_first_pass',
            field=models.IntegerField(default=0, verbose_name='Первый проход редактуры'),
        ),
        migrations.AddField(
            model_name='translationstatistics',
            name='edited_second_pass',
            field=models.IntegerField(default=0, verbose_name='Второй проход редактуры'),
        ),
        migrations.AddField(
            model_name='translationstatistics',
            name='total_rows',
            field=models.IntegerField(default=0, verbose_name='Всего строк'),
        ),
        migrations.AddField(
            model_name='translationstatistics',
            name='translated',
            field=models.IntegerField(default=0, verbose_name='Переведено'),
        ),
        migrations.AddField(
            model_name='translationstatisticschapter',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
