# Generated by Django 2.0.2 on 2018-03-31 21:20

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_add_fields_for_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationstatisticschapter',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='translation.TranslationStatisticsChapter'),
        ),
    ]
