# Generated by Django 2.0.2 on 2018-03-31 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_remove_protect_on_chapter_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationitem',
            name='statistics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translation.TranslationStatistics', verbose_name='Привязанная статистика'),
        ),
    ]
