# Generated by Django 2.0.2 on 2018-03-31 21:58

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0009_remove_protect_on_statistics_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationstatisticschapter',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=None, related_name='children', to='translation.TranslationStatisticsChapter'),
        ),
    ]
