# Generated by Django 2.0.2 on 2018-03-31 22:03

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0011_auto_20180401_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationstatisticschapter',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='translation.TranslationStatisticsChapter'),
        ),
    ]
