# Generated by Django 2.0.2 on 2018-04-07 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translation', '0012_remove_setnull_on_chapter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationitem',
            name='moderators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Модераторы'),
        ),
    ]
