# Generated by Django 2.0.2 on 2018-04-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0014_add_subscribers_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationbetalink',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
