# Generated by Django 2.0.2 on 2018-04-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0015_add_approved_field_to_betalinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationbetalink',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
