# Generated by Django 2.0.2 on 2018-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0016_add_last_update_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationbetalink',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Отклонена'),
        ),
        migrations.AlterField(
            model_name='translationbetalink',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
    ]
