# Generated by Django 2.0.2 on 2018-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0017_add_last_rejected_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationbetalink',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
