# Generated by Django 2.0.2 on 2018-08-10 10:46

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=500, verbose_name='название')),
                ('file', core.fields.FileFieldWithEnhancedUploadTo(verbose_name='файл')),
                ('extension', models.CharField(blank=True, default='', editable=False, max_length=20, verbose_name='расширение')),
            ],
            options={
                'verbose_name': 'закачка',
                'verbose_name_plural': 'закачки',
                'db_table': 'custom_downloads',
                'ordering': ('-id',),
            },
        ),
    ]
