# Generated by Django 2.0.4 on 2018-12-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_create_mailing_crontabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingtask',
            name='mailing_task',
        ),
        migrations.DeleteModel(
            name='MailingTask',
        ),
    ]
