# Generated by Django 2.0.2 on 2018-03-13 12:02

from django.db import migrations, models
import vn_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualNovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('alternative_title', models.CharField(default='', max_length=500, verbose_name='альтернативные названия')),
                ('description', models.TextField(default='', max_length=8000, verbose_name='описание')),
                ('photo', models.ImageField(upload_to=vn_core.models.posters_directory_path, verbose_name='фотография')),
                ('date_of_release', models.DateField(verbose_name='дата релиза')),
                ('vndb_id', models.IntegerField(verbose_name='id на VNDb')),
                ('steam_link', models.CharField(blank=True, max_length=400, null=True, verbose_name='ссылка в Steam')),
            ],
            options={
                'verbose_name': 'Визуальная новелла',
                'verbose_name_plural': 'Визуальные новеллы',
                'db_table': 'vncore',
            },
        ),
    ]
