# Generated by Django 2.0.2 on 2018-03-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0007_add_longevity_model'),
        ('vn_core', '0001_create_visual_novel_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualnovel',
            name='longevity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cinfo.Longevity', verbose_name='продолжительность'),
        ),
    ]
