# Generated by Django 2.0.2 on 2018-05-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0002_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualNovelStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('rate', models.IntegerField(default=0, verbose_name='оценка на VNDb')),
                ('popularity', models.IntegerField(default=0, verbose_name='популярность на VNDb')),
                ('vote_count', models.IntegerField(default=0, verbose_name='число голосов на VNDb')),
                ('visual_novel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vn_core.VisualNovel')),
            ],
            options={
                'verbose_name': 'Оценка визуальной новеллы',
                'verbose_name_plural': 'Оценки визуальных новелл',
                'db_table': 'vnstats',
            },
        ),
    ]
