# Generated by Django 2.0.2 on 2018-06-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0003_initial_vn_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualnovelstats',
            old_name='data',
            new_name='date',
        ),
    ]
