# Generated by Django 2.0.2 on 2018-03-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0003_add_many_to_many_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualnovel',
            name='alias',
            field=models.TextField(default='', max_length=30, verbose_name='алиас (до 30 символов)'),
        ),
    ]
