# Generated by Django 2.0.2 on 2018-03-14 21:25

from django.db import migrations, models
import vn_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0004_add_alias_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='VNScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(max_length=256, verbose_name='подпись')),
                ('image', models.ImageField(upload_to=vn_core.models.screenshots_directory_path, verbose_name='фотография')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
                'db_table': 'vn_screenshot',
            },
        ),
    ]
