# Generated by Django 2.0.2 on 2018-06-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0004_change_field_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visualnovel',
            options={'ordering': ('title',), 'verbose_name': 'Визуальная новелла', 'verbose_name_plural': 'Визуальные новеллы'},
        ),
        migrations.AlterField(
            model_name='vngenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres_set', to='cinfo.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='vnstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_set', to='cinfo.Staff', verbose_name='Персона'),
        ),
        migrations.AlterField(
            model_name='vnstudio',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios_set', to='cinfo.Studio', verbose_name='Студия'),
        ),
        migrations.AlterField(
            model_name='vntag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_set', to='cinfo.Tag', verbose_name='Тэг'),
        ),
    ]
