# Generated by Django 2.0.2 on 2018-07-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0005_add_translators_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnstaff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinfo.StaffRole', verbose_name='роль'),
        ),
    ]
