# Generated by Django 2.0.2 on 2018-03-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0005_add_vn_screenshot_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualnovel',
            name='genres',
            field=models.ManyToManyField(blank=True, through='vn_core.VNGenre', to='cinfo.Genre', verbose_name='жанры'),
        ),
        migrations.AlterField(
            model_name='visualnovel',
            name='staff',
            field=models.ManyToManyField(blank=True, through='vn_core.VNStaff', to='cinfo.Staff', verbose_name='создатели'),
        ),
        migrations.AlterField(
            model_name='visualnovel',
            name='studios',
            field=models.ManyToManyField(blank=True, through='vn_core.VNStudio', to='cinfo.Studio', verbose_name='студии'),
        ),
        migrations.AlterField(
            model_name='visualnovel',
            name='tags',
            field=models.ManyToManyField(blank=True, through='vn_core.VNTag', to='cinfo.Tag', verbose_name='тэги'),
        ),
    ]
