# Generated by Django 2.0.2 on 2018-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0006_change_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualnovelstats',
            name='rank_by_visits',
            field=models.IntegerField(blank=True, null=True, verbose_name='место по визитам'),
        ),
    ]
