# Generated by Django 2.0.2 on 2018-03-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0006_add_blanc_true_for_cinfo_manytomany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnscreenshot',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='подпись'),
        ),
    ]
