# Generated by Django 2.0.2 on 2018-03-15 16:22

from django.db import migrations, models
import vn_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0007_fix_screenshot_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnscreenshot',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to=vn_core.models.screenshots_mini_directory_path, verbose_name='миниатюра'),
        ),
    ]
