# Generated by Django 4.2.5 on 2023-09-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0007_add_rank_by_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualnovel',
            name='alias',
            field=models.TextField(default='', max_length=30, unique=True, verbose_name='алиас (до 30 символов)'),
        ),
    ]
