# Generated by Django 4.2.5 on 2025-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0008_alter_visualnovel_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.SlugField()),
                ('token', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
