# Generated by Django 2.0.2 on 2018-03-15 16:44

from django.db import migrations, models
import vn_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0008_add_miniature_field_to_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnscreenshot',
            name='miniature',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=vn_core.models.screenshots_mini_directory_path, verbose_name='миниатюра'),
        ),
    ]
