# Generated by Django 2.0.2 on 2018-03-15 17:34

from django.db import migrations, models
import vn_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0009_miniature_non_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnscreenshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vn_core.models.screenshots_directory_path, verbose_name='фотография'),
        ),
    ]
