# Generated by Django 4.2.5 on 2026-05-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0009_externalapiuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualnovel',
            name='nvn_link',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ссылка на НВН'),
        ),
    ]
