# Generated by Django 2.0.2 on 2018-03-15 19:23

from django.db import migrations, models
import vn_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0010_image_field_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualnovel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=vn_core.models.posters_directory_path, verbose_name='фотография'),
        ),
    ]
