# Generated by Django 2.0.2 on 2018-03-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0014_visualnovel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualnovel',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='популярность на VNDb'),
        ),
        migrations.AddField(
            model_name='visualnovel',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='число голосов на VNDb'),
        ),
    ]
