# Generated by Django 2.0.2 on 2018-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('name', models.CharField(blank=True, default='пользователь', max_length=256, null=True, verbose_name='название')),
                ('offer', models.TextField(blank=True, default='', max_length=5000, verbose_name='предложение')),
                ('email', models.CharField(max_length=256, verbose_name='почта')),
                ('is_considered', models.BooleanField(default=False, verbose_name='Рассмотрено')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Отказано')),
                ('rejected_reasons', models.TextField(blank=True, default='', max_length=5000, verbose_name='Причины отказа')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время заявки')),
            ],
            options={
                'verbose_name': 'Предложение по улучшению сайта',
                'verbose_name_plural': 'Предложения по улучшению сайта',
                'db_table': 'offers',
            },
        ),
    ]
