# Generated by Django 2.0.2 on 2018-03-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vn_core', '0002_add_longevity_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('date_of_translation', models.DateField(verbose_name='дата перевода на русский (первого)')),
                ('visual_novel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vn_core.VisualNovel')),
            ],
            options={
                'verbose_name': 'Итем чарта',
                'verbose_name_plural': 'Итемы чарта',
                'db_table': 'chart_items',
            },
        ),
    ]
