# Generated by Django 2.0.2 on 2018-04-25 21:09

from django.db import migrations, models
import django.db.models.deletion
import vn_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vn_core', '0001_new_visual_novel_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('date_of_translation', models.DateField(verbose_name='дата перевода на русский (первого)')),
                ('comment', models.TextField(blank=True, default='', max_length=5000, verbose_name='комментарий')),
                ('visual_novel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vn_core.VisualNovel')),
            ],
            options={
                'verbose_name': 'Итем чарта',
                'verbose_name_plural': 'Итемы чарта',
                'db_table': 'chart_items',
            },
        ),
        migrations.CreateModel(
            name='ChartItemScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='подпись')),
                ('image', models.ImageField(blank=True, null=True, upload_to=vn_core.models.screenshots_directory_path, verbose_name='фотография')),
                ('miniature', models.ImageField(blank=True, editable=False, null=True, upload_to=vn_core.models.screenshots_mini_directory_path, verbose_name='миниатюра')),
                ('order', models.IntegerField(default=0, verbose_name='порядок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.ChartItem')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
                'db_table': 'chart_item_to_screenshot',
            },
        ),
    ]
