# Generated by Django 2.0.2 on 2018-03-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0006_add_blanc_true_for_cinfo_manytomany'),
        ('chart', '0001_add_chart_item_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartItemScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='порядок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chart.ChartItem')),
                ('screenshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vn_core.VNScreenshot')),
            ],
            options={
                'db_table': 'chart_item_to_screenshot',
            },
        ),
    ]
