# Generated by Django 2.0.2 on 2018-03-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0006_add_blanc_true_for_cinfo_manytomany'),
        ('chart', '0002_add_screenshot_relation_to_chartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='screenshots',
            field=models.ManyToManyField(blank=True, through='chart.ChartItemScreenshot', to='vn_core.VNScreenshot', verbose_name='скриншоты'),
        ),
    ]
