# Generated by Django 2.0.2 on 2018-06-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_test_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartitem',
            options={'ordering': ('visual_novel__title',), 'verbose_name': 'Итем чарта', 'verbose_name_plural': 'Итемы чарта'},
        ),
        migrations.AlterField(
            model_name='chartitem',
            name='visual_novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vn_core.VisualNovel', verbose_name='Визуальная новелла'),
        ),
    ]
