# Generated by Django 2.0.2 on 2018-03-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_add_screenshot_to_chartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartitemscreenshot',
            name='item',
        ),
        migrations.RemoveField(
            model_name='chartitemscreenshot',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='chartitem',
            name='screenshots',
        ),
        migrations.DeleteModel(
            name='ChartItemScreenshot',
        ),
    ]
