# Generated by Django 2.0.2 on 2018-06-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinfo', '0003_add_translators_model'),
        ('chart', '0003_add_translators_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartItemTranslator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.ChartItem', verbose_name='Визуальная новелла')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinfo.TranslationLanguage', verbose_name='Язык перевода')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinfo.Translator', verbose_name='Переводчик')),
            ],
            options={
                'verbose_name': 'Перевод новеллы',
                'verbose_name_plural': 'Переводы новелл',
                'db_table': 'chart_item_to_translators',
            },
        ),
        migrations.AddField(
            model_name='chartitem',
            name='translations',
            field=models.ManyToManyField(blank=True, through='chart.ChartItemTranslator', to='cinfo.Translator', verbose_name='Переводы'),
        ),
    ]
