# Generated by Django 2.0.2 on 2018-03-14 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vn_core', '0006_add_blanc_true_for_cinfo_manytomany'),
        ('chart', '0004_remove_screenshots_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartItemScreenshot',
            fields=[
                ('vnscreenshot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vn_core.VNScreenshot')),
                ('order', models.IntegerField(default=0, verbose_name='порядок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chart.ChartItem')),
            ],
            options={
                'db_table': 'chart_item_to_screenshot',
            },
            bases=('vn_core.vnscreenshot',),
        ),
    ]
