# Generated by Django 4.0.5 on 2022-06-17 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart', '0004_add_translators_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartItemToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранные новеллы',
                'verbose_name_plural': 'Избранные новеллы',
            },
        ),
        migrations.AddField(
            model_name='chartitem',
            name='favorites',
            field=models.ManyToManyField(through='chart.ChartItemToUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chartitemscreenshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chartitemtranslator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='chartitemtouser',
            name='chart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.chartitem', verbose_name='Итем чарта'),
        ),
        migrations.AddField(
            model_name='chartitemtouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
