# Generated by Django 4.0.5 on 2022-06-23 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chart', '0005_add_chartitemtouser_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Рейтинг новеллы',
                'verbose_name_plural': 'Рейтинг новеллы',
            },
        ),
        migrations.AddField(
            model_name='chartitem',
            name='rating',
            field=models.ManyToManyField(related_name='chart_rating', through='chart.ChartRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chartitem',
            name='favorites',
            field=models.ManyToManyField(related_name='chart_favorites', through='chart.ChartItemToUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartrating',
            name='chart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.chartitem', verbose_name='Итем чарта'),
        ),
        migrations.AddField(
            model_name='chartrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='chartrating',
            constraint=models.UniqueConstraint(fields=('user', 'chart_item'), name='rating'),
        ),
    ]
