# Generated by Django 2.0.2 on 2018-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_test_vn_to_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='comment',
            field=models.TextField(default='', max_length=5000, verbose_name='комментарий'),
        ),
    ]
